export const movies = [
  {
    id: 0,
    title: "Fight Club",
    genre: "Drama",
    isFavorite: false,
    year: 1999,
    img: "https://assets.voxcinemas.com/content/Lord_of_the_Rings_1693893577.jpg",
    description:
      "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into much more.",
  },
  {
    id: 1,
    title: "The Shawshank Redemption",
    genre: "Drama",
    isFavorite: false,
    year: 1994,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLgPRlpMxqB92sJEXI2l-uNRSy5GaQqpC4Fg&usqp=CAU",
    description: "A banker named Andy Dufresne is sentenced to life in Shawshank State Penitentiary for the murder of his wife and her lover, despite maintaining his innocence. Andy befriends a fellow inmate named Red and navigates the harsh realities of prison life.",
 },
  {
    id: 2,
    title: "The Godfather",
    genre: "Crime",
    isFavorite: false,
    year: 1972,
    img: "https://socialist.net/wp-content/uploads/2022/08/godfather.png",
    description: "Frodo Baggins, along with a diverse group of companions, embarks on a perilous journey to Mount Doom to destroy a powerful ring. The fellowship faces numerous challenges and confronts the dark forces of Sauron.",
 },
  {
    id: 3,
    title: "The Dark Knight",
    genre: "Action",
    isFavorite: false,
    year: 2008,
    img: "https://wallpapers.com/images/featured/the-dark-knight-pictures-jlyjxakv2mz57z02.jpg",
    description:
      "A young hobbit, Frodo Baggins, embarks on a perilous journey to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.",
  },
  {
    id: 4,
    title: "Pulp Fiction",
    genre: "Crime",
    isFavorite: false,
    year: 1994,
    img: "https://wallpapers.com/images/hd/the-avengers-superhero-movie-eeotwqkmypkvalg9.jpg",
    description: "Frodo Baggins, along with a diverse group of companions, embarks on a perilous journey to Mount Doom to destroy a powerful ring. The fellowship faces numerous challenges and confronts the dark forces of Sauron.",
},
  {
    id: 5,
    title: "Forrest Gump",
    genre: "Drama",
    isFavorite: false,
    year: 1994,
    img: "https://4kwallpapers.com/images/walls/thumbs_2t/8772.jpg",
    description:
      "A young hobbit, Frodo Baggins, embarks on a perilous journey to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.",
  },
  {
    id: 6,
    title: "Inception",
    genre: "Sci-Fi",
    isFavorite: false,
    year: 2010,
    img: "https://i.pinimg.com/originals/53/05/dd/5305ddfc3964afe2c0d224f141856660.jpg",
    description: "A banker named Andy Dufresne is sentenced to life in Shawshank State Penitentiary for the murder of his wife and her lover, despite maintaining his innocence. Andy befriends a fellow inmate named Red and navigates the harsh realities of prison life.",
 },
  {
    id: 7,
    title: "The Matrix",
    genre: "Action",
    isFavorite: false,
    year: 1999,
    img: "https://i.kinja-img.com/image/upload/c_fill,h_900,q_60,w_1600/2e5f6da2b028321237b3643150014784.jpg",
    description:
      "A young hobbit, Frodo Baggins, embarks on a perilous journey to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.",
  },
  {
    id: 8,
    title: "Schindler's List",
    genre: "Biography",
    isFavorite: false,
    year: 1993,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRI12gG1P1jrKAF4p4WMqwEAoUOg-5Q1jEWYsel99xS1CYBdCJow9gm-pHCES845cjCI1k&usqp=CAU",
    description: "Frodo Baggins, along with a diverse group of companions, embarks on a perilous journey to Mount Doom to destroy a powerful ring. The fellowship faces numerous challenges and confronts the dark forces of Sauron.",
},
  {
    id: 9,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    genre: "Adventure",
    isFavorite: false,
    year: 2001,
    img: "https://www.netflix-nederland.nl/wp-content/uploads/2018/12/The-Lord-of-the-Rings-Return-of-the-King-Netflix-1.jpg",
    description:
      "A young hobbit, Frodo Baggins, embarks on a perilous journey to destroy a powerful ring and save Middle-earth from the Dark Lord Sauron.",
  },
];
